# Generated by Django 5.2.3 on 2025-12-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('hs_code', models.CharField(max_length=6)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
