# Generated by Django 5.2 on 2025-04-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_department_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
